repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        verbose: true
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings==1.5.0]
        verbose: true

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: mypy_metricflow
        args: [--ignore-missing-imports, --show-error-codes]
        additional_dependencies:
          [
            sqlalchemy,
            types-flask,
            types-requests,
            types-PyYAML,
            types-jinja2,
            types-attrs,
            types-tabulate,
            pytest,
            python-dateutil,
            types-python-dateutil,
            dbt-core,
            pydantic,
          ]
